#!/usr/bin/env node
/* ==========================================================================
   Generates the checklist, prompt-library and audit-question docs from the
   same data files the website uses, so the two can never drift apart.

   Usage:  node tools/build-docs.js
   ========================================================================== */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const JS = path.join(ROOT, 'assets', 'js');
const DOCS = path.join(ROOT, 'docs');

const src = ['data.js', 'prompts.js', 'checklists.js']
  .map(f => fs.readFileSync(path.join(JS, f), 'utf8')).join('\n');
const { PILLARS, QUESTIONS, PROMPTS, PROMPT_CATEGORIES, CHECKLISTS } =
  new Function(src + '\nreturn {PILLARS, QUESTIONS, PROMPTS, PROMPT_CATEGORIES, CHECKLISTS};')();

const NOTE = '<!-- Generated by tools/build-docs.js — edit the data in assets/js/, not this file. -->\n\n';
const write = (file, body) => {
  fs.writeFileSync(path.join(DOCS, file), NOTE + body);
  console.log('wrote docs/' + file + '  (' + body.length + ' chars)');
};

/* ------------------------------------------------------------- checklists */
function checklistDoc(track, title, lead) {
  const list = CHECKLISTS[track];
  let n = 0;
  let md = '# ' + title + '\n\n' + lead + '\n\n' + list.intro + '\n\n';
  md += '> Tick these off in the browser version at `index.html` if you would rather not print it —\n';
  md += '> progress saves automatically. Items with an **AI** note have a matching prompt in\n';
  md += '> [the prompt library](04-ai-prompt-library.md).\n\n';

  list.groups.forEach(g => {
    md += '## ' + g.icon + ' ' + g.name + '\n\n' + g.note + '\n\n';
    g.items.forEach(it => {
      n++;
      md += '- [ ] ' + it.x + '  \n  <sub>⏱ ' + it.t +
            (it.ai ? '  ·  🤖 AI prompt: **' + (PROMPTS.find(p => p.id === it.ai) || {}).title + '**' : '') +
            '</sub>\n';
    });
    md += '\n';
  });
  md += '---\n\n**' + n + ' items total.**\n';
  return md;
}

write('02-seo-checklist.md', checklistDoc('seo',
  'SEO checklist — getting found',
  'Everything that makes a search engine able to find you, understand you and rank you. Work top to bottom; the groups are ordered by return on effort for an independent restaurant.'));

write('03-aeo-checklist.md', checklistDoc('aeo',
  'AEO checklist — getting recommended',
  'Everything that makes an AI assistant able to find, trust and correctly recommend you. Do the [SEO checklist](02-seo-checklist.md) first — most of it feeds this one.'));

/* -------------------------------------------------------------- prompts */
{
  let md = '# AI prompt library\n\n';
  md += 'Thirty prompts for restaurant SEO and AEO work, written the way that actually gets useful\n';
  md += 'output. Replace anything in `{{braces}}` with your own details — or use the browser version\n';
  md += 'at `index.html`, which fills them in for you once you complete the "Add your restaurant" form.\n\n';
  md += 'Every prompt follows the same shape: role, real context, a specific task, a required output\n';
  md += 'format, and an instruction not to invent facts.\n\n';

  md += '## Contents\n\n';
  PROMPT_CATEGORIES.forEach(c => {
    const inCat = PROMPTS.filter(p => p.cat === c.id);
    md += '- **' + c.name + '** (' + inCat.length + ') — ' + c.blurb + '\n';
  });
  md += '\n---\n\n';

  PROMPT_CATEGORIES.forEach(c => {
    md += '## ' + c.name + '\n\n' + c.blurb + '\n\n';
    PROMPTS.filter(p => p.cat === c.id).forEach(p => {
      md += '### ' + p.title + '\n\n';
      md += '**When:** ' + p.when + '\n\n';
      md += '**Why it works:** ' + p.why + '\n\n';
      md += '```text\n' + p.prompt + '\n```\n\n';
    });
  });

  md += '---\n\n## The rules that keep AI useful\n\n';
  md += '**Let AI do:** menu-to-HTML conversion, dish descriptions from ingredients you supply, schema\n';
  md += 'markup, FAQ drafts, review-reply options, bulk title tags, review theme analysis, translating\n';
  md += 'technical reports, content calendars, and telling you which facts your site is missing.\n\n';
  md += '**Never let AI do:** state your hours, prices or address unchecked; invent dishes, ingredients\n';
  md += 'or allergen information; claim awards or press you do not have; write or auto-reply to reviews;\n';
  md += 'name local landmarks it has not confirmed; or publish anything to your Google profile\n';
  md += 'unsupervised.\n\n';
  md += '**The allergen rule:** never publish AI-generated allergen or dietary information without your\n';
  md += 'kitchen checking it line by line. An assistant will describe a dish as gluten-free from the name\n';
  md += 'alone. That is a medical and legal risk, and the one place in this playbook where speed is not\n';
  md += 'worth it.\n';
  write('04-ai-prompt-library.md', md);
}

/* ------------------------------------------------------ audit questions */
{
  let md = '# The audit questions\n\n';
  md += 'The full question set behind the self-audit, with how to check each one, why it matters, what\n';
  md += 'to do about it, and where AI helps. Run it interactively at `index.html` to get a score and a\n';
  md += 'prioritized plan, or work through it here on paper.\n\n';

  md += '## How scoring works\n\n';
  md += 'Each pillar carries a weight; each question carries a weight inside its pillar. Answers score\n';
  md += '**Yes** = 1.0, **Partly** = 0.6, **Not sure** = 0.25, **No** = 0. Pillars you have not answered\n';
  md += 'at all are excluded and the remaining weights are renormalized, so a partly-finished audit\n';
  md += 'still scores honestly.\n\n';

  md += '| Pillar | Weight | Questions | Why it carries that weight |\n|---|---|---|---|\n';
  PILLARS.forEach(p => {
    md += '| ' + p.icon + ' ' + p.name + ' | ' + p.weight + '% | ' +
          QUESTIONS.filter(q => q.pillar === p.id).length + ' | ' + p.ownerNote + ' |\n';
  });
  md += '\n**Score bands:** 85+ Strong · 70–84 Solid with gaps · 50–69 Half built · 30–49 Losing\n';
  md += 'customers · under 30 Effectively invisible.\n\n---\n\n';

  PILLARS.forEach(p => {
    md += '## ' + p.icon + ' ' + p.name + '  \n<sub>' + p.weight + '% of your score</sub>\n\n';
    md += p.blurb + '\n\n';
    QUESTIONS.filter(q => q.pillar === p.id).forEach(q => {
      md += '### ' + q.q + '\n\n';
      md += '- **How to check:** ' + q.check + '\n';
      md += '- **Why it matters:** ' + q.why + '\n';
      md += '- **What to do:** ' + q.fix + '\n';
      md += '- **How AI helps:** ' + q.ai + '\n';
      md += '- <sub>Impact: ' + q.impact + ' · Effort: ' + q.effort + '</sub>\n\n';
    });
  });
  write('05-audit-questions.md', md);
}

console.log('\nDone. ' + QUESTIONS.length + ' questions, ' + PROMPTS.length + ' prompts, ' +
  Object.values(CHECKLISTS).reduce((n, l) => n + l.groups.reduce((m, g) => m + g.items.length, 0), 0) +
  ' checklist items.');
