#!/usr/bin/env node
/* ==========================================================================
   Generates the checklist, prompt-library and audit-question docs from the
   same data files the website uses, so the two can never drift apart.

   Usage:  node tools/build-docs.js
   ========================================================================== */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const JS = path.join(ROOT, 'assets', 'js');
const DOCS = path.join(ROOT, 'docs');

const src = ['data.js', 'prompts.js', 'checklists.js', 'checker-spec.js']
  .map(f => fs.readFileSync(path.join(JS, f), 'utf8')).join('\n');
/* The data files assign to `window` for the browser; give them one. */
const { PILLARS, QUESTIONS, PROMPTS, PROMPT_CATEGORIES, CHECKLISTS,
        RESTAURANT_FIELDS, PAGE_CHECKS, FOOD_TYPES } =
  new Function('window', src + '\nreturn {PILLARS, QUESTIONS, PROMPTS, PROMPT_CATEGORIES, CHECKLISTS,' +
    ' RESTAURANT_FIELDS, PAGE_CHECKS, FOOD_TYPES};')({});

const NOTE = '<!-- Generated by tools/build-docs.js — edit the data in assets/js/, not this file. -->\n\n';
const FOOTER = '\n\n---\n\n_From [The Restaurant SEO &amp; AEO Playbook](../README.md) by ' +
  '[Dineline](https://dineline.co/) — done-for-you restaurant marketing, tracked to the dollar._\n';
const write = (file, body) => {
  fs.writeFileSync(path.join(DOCS, file), NOTE + body.replace(/\n+$/, '') + FOOTER);
  console.log('wrote docs/' + file + '  (' + body.length + ' chars)');
};

/* ------------------------------------------------------------- checklists */
function checklistDoc(track, title, lead) {
  const list = CHECKLISTS[track];
  let n = 0;
  let md = '# ' + title + '\n\n' + lead + '\n\n' + list.intro + '\n\n';
  md += '> Tick these off in the browser version at `index.html` if you would rather not print it —\n';
  md += '> progress saves automatically. Items with an **AI** note have a matching prompt in\n';
  md += '> [the prompt library](04-ai-prompt-library.md).\n\n';

  list.groups.forEach(g => {
    md += '## ' + g.icon + ' ' + g.name + '\n\n' + g.note + '\n\n';
    g.items.forEach(it => {
      n++;
      md += '- [ ] ' + it.x + '  \n  <sub>⏱ ' + it.t +
            (it.ai ? '  ·  🤖 AI prompt: **' + (PROMPTS.find(p => p.id === it.ai) || {}).title + '**' : '') +
            '</sub>\n';
    });
    md += '\n';
  });
  md += '---\n\n**' + n + ' items total.**\n';
  return md;
}

write('02-seo-checklist.md', checklistDoc('seo',
  'SEO checklist — getting found',
  'Everything that makes a search engine able to find you, understand you and rank you. Work top to bottom; the groups are ordered by return on effort for an independent restaurant.'));

write('03-aeo-checklist.md', checklistDoc('aeo',
  'AEO checklist — getting recommended',
  'Everything that makes an AI assistant able to find, trust and correctly recommend you. Do the [SEO checklist](02-seo-checklist.md) first — most of it feeds this one.'));

/* -------------------------------------------------------------- prompts */
{
  let md = '# AI prompt library\n\n';
  md += 'Thirty prompts for restaurant SEO and AEO work, written the way that actually gets useful\n';
  md += 'output. Replace anything in `{{braces}}` with your own details — or use the browser version\n';
  md += 'at `index.html`, which fills them in for you once you complete the "Add your restaurant" form.\n\n';
  md += 'Every prompt follows the same shape: role, real context, a specific task, a required output\n';
  md += 'format, and an instruction not to invent facts.\n\n';

  md += '## Contents\n\n';
  PROMPT_CATEGORIES.forEach(c => {
    const inCat = PROMPTS.filter(p => p.cat === c.id);
    md += '- **' + c.name + '** (' + inCat.length + ') — ' + c.blurb + '\n';
  });
  md += '\n---\n\n';

  PROMPT_CATEGORIES.forEach(c => {
    md += '## ' + c.name + '\n\n' + c.blurb + '\n\n';
    PROMPTS.filter(p => p.cat === c.id).forEach(p => {
      md += '### ' + p.title + '\n\n';
      md += '**When:** ' + p.when + '\n\n';
      md += '**Why it works:** ' + p.why + '\n\n';
      md += '```text\n' + p.prompt + '\n```\n\n';
    });
  });

  md += '---\n\n## The rules that keep AI useful\n\n';
  md += '**Let AI do:** menu-to-HTML conversion, dish descriptions from ingredients you supply, schema\n';
  md += 'markup, FAQ drafts, review-reply options, bulk title tags, review theme analysis, translating\n';
  md += 'technical reports, content calendars, and telling you which facts your site is missing.\n\n';
  md += '**Never let AI do:** state your hours, prices or address unchecked; invent dishes, ingredients\n';
  md += 'or allergen information; claim awards or press you do not have; write or auto-reply to reviews;\n';
  md += 'name local landmarks it has not confirmed; or publish anything to your Google profile\n';
  md += 'unsupervised.\n\n';
  md += '**The allergen rule:** never publish AI-generated allergen or dietary information without your\n';
  md += 'kitchen checking it line by line. An assistant will describe a dish as gluten-free from the name\n';
  md += 'alone. That is a medical and legal risk, and the one place in this playbook where speed is not\n';
  md += 'worth it.\n';
  write('04-ai-prompt-library.md', md);
}

/* ------------------------------------------------------ audit questions */
{
  let md = '# The audit questions\n\n';
  md += 'The full question set behind the self-audit, with how to check each one, why it matters, what\n';
  md += 'to do about it, and where AI helps. Run it interactively at `index.html` to get a score and a\n';
  md += 'prioritized plan, or work through it here on paper.\n\n';

  md += '## How scoring works\n\n';
  md += 'Each pillar carries a weight; each question carries a weight inside its pillar. Answers score\n';
  md += '**Yes** = 1.0, **Partly** = 0.6, **Not sure** = 0.25, **No** = 0. Pillars you have not answered\n';
  md += 'at all are excluded and the remaining weights are renormalized, so a partly-finished audit\n';
  md += 'still scores honestly.\n\n';

  md += '| Pillar | Weight | Questions | Why it carries that weight |\n|---|---|---|---|\n';
  PILLARS.forEach(p => {
    md += '| ' + p.icon + ' ' + p.name + ' | ' + p.weight + '% | ' +
          QUESTIONS.filter(q => q.pillar === p.id).length + ' | ' + p.ownerNote + ' |\n';
  });
  md += '\n**Score bands:** 85+ Strong · 70–84 Solid with gaps · 50–69 Half built · 30–49 Losing\n';
  md += 'customers · under 30 Effectively invisible.\n\n---\n\n';

  PILLARS.forEach(p => {
    md += '## ' + p.icon + ' ' + p.name + '  \n<sub>' + p.weight + '% of your score</sub>\n\n';
    md += p.blurb + '\n\n';
    QUESTIONS.filter(q => q.pillar === p.id).forEach(q => {
      md += '### ' + q.q + '\n\n';
      md += '- **How to check:** ' + q.check + '\n';
      md += '- **Why it matters:** ' + q.why + '\n';
      md += '- **What to do:** ' + q.fix + '\n';
      md += '- **How AI helps:** ' + q.ai + '\n';
      md += '- <sub>Impact: ' + q.impact + ' · Effort: ' + q.effort + '</sub>\n\n';
    });
  });
  write('05-audit-questions.md', md);
}

/* --------------------------------------------------- checker reference */
{
  const SEV = { critical: 'Critical', important: 'Important', nice: 'Nice to have' };
  let md = '# What the site checker looks for\n\n';
  md += 'The checker at `index.html#checker` reads whatever you paste — a JSON-LD block, your whole\n';
  md += 'page source, or an uploaded file — and reports what is missing, what is malformed, and what\n';
  md += 'is a policy risk. This is the full rule set it applies.\n\n';
  md += 'Severity means: **Critical** breaks something or risks a penalty · **Important** costs you\n';
  md += 'visibility · **Nice to have** is worth doing once the rest is done.\n\n---\n\n';

  md += '## Structured data fields\n\n';
  md += 'Checked against your `Restaurant` block. Types accepted as a food business: ' +
        FOOD_TYPES.map(t => '`' + t + '`').join(', ') + '.\n\n';
  ['critical', 'important', 'nice'].forEach(sev => {
    const list = RESTAURANT_FIELDS.filter(f => f.sev === sev);
    if (!list.length) return;
    md += '### ' + SEV[sev] + '\n\n';
    list.forEach(f => {
      md += '#### `' + f.k + '` — ' + f.label + '\n\n';
      md += '- **Why it matters:** ' + f.why + '\n';
      md += '- **What to do:** ' + f.fix + '\n\n';
    });
  });

  md += '## Shape and policy checks\n\n';
  md += 'Beyond "is the field there", the checker also catches the mistakes that look fine until\n';
  md += 'something reads them:\n\n';
  [
    ['Critical', 'Invalid JSON in a structured data block — search engines skip these silently'],
    ['Critical', 'Address written as one string instead of a `PostalAddress` object'],
    ['Critical', 'A `hasMenu` link pointing at a PDF — the most expensive mistake in restaurant SEO'],
    ['Critical', 'Placeholder values (`FILL_IN`, `example.com`, bracketed text) still live in the markup'],
    ['Critical', 'Self-serving `aggregateRating` or `review` on your own site — a Google guideline violation'],
    ['Important', 'A block that only parses after repairing smart quotes, trailing commas or a BOM'],
    ['Important', 'Missing `@context`'],
    ['Important', 'Marked up as a generic `LocalBusiness` rather than a food-business type'],
    ['Important', 'More than one restaurant block on the same page'],
    ['Important', 'Hours as free-text `openingHours` instead of `openingHoursSpecification`'],
    ['Important', 'Opening times that are not `HH:MM`'],
    ['Important', 'An incomplete `PostalAddress`'],
    ['Important', 'A business name containing marketing language ("best", "#1", "award-winning")'],
    ['Important', 'Insecure `http://` URLs in `url`, `image` or `hasMenu`'],
    ['Nice to have', 'Phone number with no country code, or an unusual format'],
    ['Nice to have', 'Malformed `priceRange`'],
    ['Nice to have', 'Fewer than three profiles in `sameAs`'],
    ['Nice to have', 'Days absent from your hours, and no holiday or special hours declared'],
    ['Nice to have', 'FAQ questions with no answer, or answers under 40 characters'],
    ['Nice to have', 'Menu items with no price or no description'],
    ['Nice to have', 'Event `startDate` with no timezone offset'],
    ['Nice to have', 'Microdata instead of JSON-LD']
  ].forEach(([sev, txt]) => { md += '- **' + sev + '** — ' + txt + '\n'; });
  md += '\n';

  md += '## On-page checks\n\n';
  md += 'These run when you paste your full page source rather than just a schema block.\n\n';
  md += '| Check | Severity | Why it matters |\n| --- | --- | --- |\n';
  PAGE_CHECKS.forEach(c => {
    md += '| ' + c.label + ' | ' + SEV[c.sev] + ' | ' + c.why + ' |\n';
  });
  md += '\n## What it cannot see\n\n';
  md += 'The checker reads what you give it, in your browser. It cannot fetch your live site, and it\n';
  md += 'has no view of your Google Business Profile, your reviews, your directory listings or what\n';
  md += 'AI assistants currently say about you. Those are covered by the\n';
  md += '[full audit](05-audit-questions.md) and the [checklists](02-seo-checklist.md).\n';
  write('08-site-checker.md', md);
}

console.log('\nDone. ' + QUESTIONS.length + ' questions, ' + PROMPTS.length + ' prompts, ' +
  Object.values(CHECKLISTS).reduce((n, l) => n + l.groups.reduce((m, g) => m + g.items.length, 0), 0) +
  ' checklist items.');
